redhat:
  hosts:
    sleet:
      fs_list: "/data /opt/containers /opt/acme /etc /var/lib/docker/volumes /root"

    alcyone:
      fs_list: "/root /etc /var/lib/docker/swarm"

    atlas:
      fs_list: "/root /etc /var/lib/docker/swarm"

    electra:
      fs_list: "/root /etc /var/lib/docker/swarm"

    flake:
      fs_list: "/etc /opt /root /home /var/log /var/adm /var/db /var/mail /var/spool /var/lib"

    blizzard:
      fs_list: "/opt/containers /opt/acme /var/www /etc/nginx/conf.d"

freebsd:
  hosts:
    gemini:
      ansible_python_interpreter: /usr/local/bin/python
      ansible_perl_interpreter: /usr/local/bin/perl
    frost:
      ansible_python_interpreter: /usr/local/bin/python
      ansible_perl_interpreter: /usr/local/bin/perl

bastions:
  frost:

docker:
  sleet:
  alcyone:
  atlas:
  electra:

web:
  sleet:
  gemini:
  blizzard:
  frost:

ssh:
  frost:
  gemini: